### ISSUE TITLE
How do you set theme variables?

### ISSUE THREAD

**Issue by jf908** [hyoban/shadcn-vue-unocss-starter#8]
### Clear and concise description of the problem

Do you know if there is a good way to set the theme colours with this preset?

I know that with `cssVariables: true` it's possibly to just manually override them but I assume there must be some config to edit shadcn's theme variables before they are generated, including a way to easily set light/dark variables separately.

### Suggested solution

It would be great if this repo included an example for this, if possible.

### Alternative

If you've got no ideas, feel free to close.

### Additional context

This is a great resource, thanks for creating it!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/hyoban/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/hyoban/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
https://github.com/hyoban/unocss-preset-shadcn/issues/3

Does this work for you? Sorry for missing documentation in the readme.

**Comment by jf908** [comment]
Perfect, I somehow missed that when I looked at the d.ts. Thank you!
